### ISSUE TITLE
После обновления EditDocs при экспорте в выборке параметров исчезло поле id

### ISSUE THREAD

**Issue by Dmi3yy** [Grinyaha/editDocs#11]
После обновления EditDocs при экспорте в выборке параметров исчезло поле id http://joxi.ru/1A5QXz7tDJGB5A    Очень неудобно, можно его как-то вернуть?

**Comment by Grinyaha** [comment]
ID по умолчанию всегда экспортируется теперь.

**Comment by Aharito** [comment]
> ID по умолчанию всегда экспортируется теперь.

Сбивает с толку то, что об этом не сказано нигде. Было бы прекрасно указать это в селекте или просто в описании.

### В селекте:
![image](https://user-images.githubusercontent.com/6253807/77247714-464ae980-6c66-11ea-83f2-54fb763efd9d.png)


### В описании:
![image](https://user-images.githubusercontent.com/6253807/77247740-709ca700-6c66-11ea-8a5d-8aad1211c95f.png)

**Comment by Grinyaha** [comment]
Добавил.
