### ISSUE TITLE
Проблема при импорте 

### ISSUE THREAD

**Issue by sergey-yabloncev** [Grinyaha/editDocs#4]
При импорте если передавать  published он попросту игнорируется 
приходится повторно заливать и делать апдейт.

Еще не всегда после загрузки файла вылезает форма с настройками приходится убирать у класса setting display: none

**Comment by Grinyaha** [comment]
Только что проверил импорт с published = 0, все ровно отработало. Может у вас старая версия? Попробуйте из extras переустановить модуль.
На счет второго бага сказать сложно, не встречал. Сам пользуюсь модулем постоянно.

**Comment by sergey-yabloncev** [comment]
Да это по всей видимости косяк в modx. 
если импортировать с published = 0 и pub_date то чек публиковать все равно проставляется.
Та же беда если вручную добавлять документы если стоит pub_date чек published не снимается

**Comment by sergey-yabloncev** [comment]
Что интересно при апдейте он все таки снимается но через modx не убирается
