### ISSUE TITLE
CSV custom separator

### ISSUE THREAD

**Issue by sashabeep** [Grinyaha/editDocs#5]
Невозможно задать другой разделитель при экспорте в CSV. ; часто используется в поле content, файл экспорта становится непригодным

**Comment by Grinyaha** [comment]
Добавлю в следующей версии.

**Comment by sashabeep** [comment]
А как можно пропатчить текущую?

**Comment by Grinyaha** [comment]
Поменять  самому разделитель в методе класса отвечающем за экспорт. Это все в файле ajax.php находится вроде как.

**Comment by sashabeep** [comment]
https://github.com/Grinyaha/editDocs/blob/150aa6beb6a2f157f8b25b8989e3e0ea74e27e3a/assets/modules/editdocs/ajax.php#L462-L463

**Comment by Grinyaha** [comment]
Вроде оно

**Comment by Grinyaha** [comment]
В последней версии добавлен выбор разделителя
