### ISSUE TITLE
3 предложения:)

### ISSUE THREAD

**Issue by webber12** [Grinyaha/editDocs#7]
1. объединить процесс обновления и добавления новых. Пользователи путаются, да и ни к чему это - проще, если система автоматом из одного файла распознает, что новое, а что существует.
2. оптимизировать процесс сохранения при апдейте - совершенно не нужно создавать документ и сохранять его при редактировании каждого поля - https://github.com/Grinyaha/editDocs/blob/master/assets/modules/editdocs/ajax.php#L270-L272 в цикле перебора ключей, достаточно собрать все ключи и обновить документ один раз
3. добавить генерацию событий, чтобы можно было манипулировать созданными данными также, как теми, что создаются вручную (для этого надо вызывать сохранение как $doc->save(true);

Ради интереса можно глянуть, как это делал я под свои нужды - https://github.com/webber12/editDocs/blob/master/ajax.php#L260-L310 :)

**Comment by Grinyaha** [comment]
Предложения разумные. Думаю добавлю все. Если что, обращусь, спасибо :)

**Comment by Grinyaha** [comment]
Сделано.
