### ISSUE TITLE
Как можно подружить MultiCategories с EditDocs?

### ISSUE THREAD

**Issue by ivan-s-1** [Grinyaha/editDocs#9]
Как можно подружить EditDocs с MultiCategories?
github.com/Pathologic/MultiCategories

**Comment by Grinyaha** [comment]
Скорее всего никак. У MultiCategories используется своя таблица в БД, где хранятся id связанных ресурсов.

**Comment by ivan-s-1** [comment]
А как то можно заставить работать с др. таблицей дополнительной ?

**Comment by Grinyaha** [comment]
> А как то можно заставить работать с др. таблицей дополнительной ?

А как вы это видите? как в режиме редактирования основных полей, чтобы можно было быстро менять id дополнительных категорий?

**Comment by ivan-s-1** [comment]
Есть плагин 
https://github.com/Pathologic/MultiCategories
он пишет данные в базу в свою таблицу site_content_categories вот в таком формате
CREATE TABLE `evo_site_content_categories` (
  `doc` int(10) NOT NULL,
  `category` int(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

doc это id документа в котором произвели привязку к категории
category - здесь id документов которые подвязаны как категории

Соотвественно, потом удобно очень делать выборку например в каталоге какого то контента, используя эти данные. Например у нас есть папка в нее загружены профиля. Также у нас есть папка с категориями, профиля подвязаны к этим категориям с использованием этого плагина.

Делаем сниппет в каталоге
получаем данные из той таблицы
$sql_profiles = $modx->db->query('SELECT DISTINCT doc FROM evo_site_content_categories WHERE category IN ('.$list_catalog_separator.')');
$query_profiles = $modx->db->makeArray($sql_profiles);
и потом это отправляем в Doclister на вывод. 
Это работает в разы быстрее, чем мы будем подвязывать категории хранимые например в Tv параметрах. 

А связка нужна с др. таблицей для того, чтоб можно было это все импортировать\экспортировать\править в EditDocs )

Готов оплатить эту доработку! Я думаю многим она интересна будет в использовании, потому что если хранить параметры каталога в tv выборка потом все равно получается не очень быстрая, а когда своя таблица такая есть под это дело, то можно быстро очень придумать разные прикольные штуки для каталогов.

**Comment by Grinyaha** [comment]
> Есть плагин
> https://github.com/Pathologic/MultiCategories
> он пишет данные в базу в свою таблицу site_content_categories вот в таком формате
> CREATE TABLE `evo_site_content_categories` (
> `doc` int(10) NOT NULL,
> `category` int(10) NOT NULL
> ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
> 
> doc это id документа в котором произвели привязку к категории
> category - здесь id документов которые подвязаны как категории
> 
> Соотвественно, потом удобно очень делать выборку например в каталоге какого то контента, используя эти данные. Например у нас есть папка в нее загружены профиля. Также у нас есть папка с категориями, профиля подвязаны к этим категориям с использованием этого плагина.
> 
> Делаем сниппет в каталоге
> получаем данные из той таблицы
> $sql_profiles = $modx->db->query('SELECT DISTINCT doc FROM evo_site_content_categories WHERE category IN ('.$list_catalog_separator.')');
> $query_profiles = $modx->db->makeArray($sql_profiles);
> и потом это отправляем в Doclister на вывод.
> Это работает в разы быстрее, чем мы будем подвязывать категории хранимые например в Tv параметрах.
> 
> А связка нужна с др. таблицей для того, чтоб можно было это все импортировать\экспортировать\править в EditDocs )
> 
> Готов оплатить эту доработку! Я думаю многим она интересна будет в использовании, потому что если хранить параметры каталога в tv выборка потом все равно получается не очень быстрая, а когда своя таблица такая есть под это дело, то можно быстро очень придумать разные прикольные штуки для каталогов.

Я понимаю как работает MultiCategories. Я не очень понимаю как вы видите работу EditDocs одновременно с MultiCategories. Если не сложно, сделайте пожалуйста ТЗ со схемами для наглядности. Можно либо сюда или на почту 9189966@gmail.com посмотрю насколько это все затратно по времени.

**Comment by ivan-s-1** [comment]
Написал на почту.

**Comment by Grinyaha** [comment]
Добавлено в последней версии.
